name: "Publish to prod v1.0.0"

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  statuses: write

jobs:
  get_packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.step.outputs.packages }}
      latest_tag: ${{ steps.tag.outputs.latest_tag }}
    steps:
      - uses: vent-io/vent-io/.github/actions/get_packages@main
        id: step
      - id: tag
        run: 'echo "latest_tag="$(git describe --abbrev=0 --tags) >> $GITHUB_OUTPUT'
      - run: "echo  Latest tag is $(git describe --abbrev=0 --tags)"

  build:
    name: Build ${{ matrix.packages.name }}
    needs: get_packages
    runs-on: ubuntu-latest
    env:
      working-directory: src/${{ matrix.packages.name }}
    strategy:
      matrix:
        packages: ${{ fromJSON(needs.get_packages.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Build package
        run: pdm build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
