name: "Precheck plan terrafrom v1.0.2"

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main, dev]

jobs:
  check_if_terraform_changed:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if terraform files changed
        id: check
        run: |
          git diff --name-only HEAD^ | grep -q '^infrastructure/' && echo "changed=true" >> $GITHUB_OUTPUT || echo "changed=false >> $GITHUB_OUTPUT"
  get_packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.step.outputs.packages }}
    needs: check_if_terraform_changed
    steps:
      - uses: vent-io/vent-io/.github/actions/get_packages@main
        id: step
  plan:
    needs: [check_if_terraform_changed, get_packages]
    if: ${{ needs.check_if_terraform_changed.outputs.changed == 'true' }}
    uses: vent-io/vent-io/.github/workflows/precheck_terraform_plan.yaml@main
    with:
      packages_json: ${{ needs.get_packages.outputs.packages }}
      working_dir: infrastructure
      tf_module_enabled: true
      env:
        ${{ ((github.event_name == 'workflow_dispatch') && github.event.inputs.environment) ||
        ((((github.head_ref || github.ref_name) == 'main') && 'uat') || 'dev') }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_TOKEN: ${{ secrets.GH_APP_TOKEN }}

  print_summary:
    runs-on: ubuntu-latest
    needs: [plan, check_if_terraform_changed]
    if: ${{ needs.check_if_terraform_changed.outputs.changed == 'true' }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: summary.md

      - name: Read file
        id: read_file
        uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b
        with:
          path: summary.md

      - name: Print summary
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{ steps.read_file.outputs.content }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
